### ISSUE TITLE
0crat was not invite users with uppercase letter in github login

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#120]
![image](https://user-images.githubusercontent.com/2982959/30829673-276f68bc-a24a-11e7-9953-d0ffafae111a.png)

I avoid this over lowercase name. It's accepted. But this is wrong.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF this is fixed, thanks for reporting.

**Comment by DronMDF** [comment]
This is not fixed.
![image](https://user-images.githubusercontent.com/2982959/31048298-ffe4abc2-a622-11e7-9af9-d91d1588e6b7.png)
I try now, problem still present.

**Comment by yegor256** [comment]
@DronMDF I just double checked, it works. Most probably, you were trying the old version. Now it definitely works. Sorry for confusion.

**Comment by DronMDF** [comment]
![image](https://user-images.githubusercontent.com/2982959/31146059-1c908f30-a88e-11e7-88e4-f5466e383e89.png)

This is a fixed now. Thank's.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#120` was not in scope
